version: '3.3'
services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      LANG: C.UTF-8
    ports:
      - '3306:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  app:
    links:
      - 'db'
    build: ./
    ports:
      - '8000:5000'
    depends_on:
      - 'db'