version: '3.3'
services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
  app:
    links:
      - 'db'
    build: ./
    ports:
      - '8000:5000'
    depends_on:
      - 'db'